# Generated by Django 2.2.5 on 2019-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='auto_images'),
        ),
    ]
